language: node_js
node_js:
- 0.12.0
deploy:
  provider: npm
  email: simbo@simbo.de
  api_key: ${NPM_API_KEY}
  on:
    tags: true
    repo: simbo/gulpplug
env:
  global:
  - secure: fjKBiGkulG2kzyb1hXMiJXmT4kga2FHifTCs5qKhVpRxfh1qiJSiYdtU/Gn6kMzVP+VDTbJB2NSX96gsBKbsHbfphIoFdeinJ9BhlWJ37Xdd8V5OBLC0nf1wDK1T0XO7fmPvpCXeZhvoSc7xPiaFPFmitgQQN8XCPAy9swOeGCawIZliEGeJCFyRaeWv6hzCfk1cwlKSTy4uqipMTKzWXYcHGpkbrm3iO+JVlqmO53xdMtTaqlaDw60jJwxJHKJEio5434wAV8RKkeKCMQ+RzKW4VFXSp/fJmEvq9NBtDM7Ser3CpgihYbdDVKd8NDBT6BJdh/Da2jWcWO2ltBagiVWpO9r/J9YkEIvQ5+0RmOJWsgh4HPlX+spmgyUNo/1jrdcD75G/I7+UA8ZBRwIh7ezltIB5dr1JIS9A1CwQSwbegLX9xmZLKiiTxNskoRJLfbazxQB+uPVmfkHgtFejLLMQ+OrUa+dXsdO8zBmTlnudxXinrsAKFfmY3MPLv667xY+AmBaZNWJlA7kywVT2iFEvtZzIsnVrlWCI4Prk+1AfhMb7DD2YQEXDrY5UvKMzkMEJPCBijDY8UgO/TaYHHGOGYuDm1m8PBNbnBtpiRBVUrhUmp3KgdwfF8qVcCJqQU9431lBjm0/kFtjITqY/l2edEnyS7JwrfW/Y6ZIA1TY=
  - secure: B8d8mMmNGhtn/8Mhmg7jlWSndJADWjHMcpQtTj3cHPzhuaoAx8jr+7CkUqw72WzjrfXHZyyLg5vHpwhJpz7yCSz21yMT0T2TvOnTWjTCtJeRLpOlAnD8iLURW45LqgyLFiEAWAArMVSuX7EMoSrSTwaMeQVc0QTbZtAFLdHOA6uuYp/Y1CC7FRnKfklOawYwSYsR5DDsavtRkHQqMTgIHhcxVmvKt7uK0ZCrj+LnlM4VMzkNQ6OaSgQ2/wNTOMgYGK0Lup5U+1d4hAMXoPDIuppuuCeYnWy2cpoU1hOncMKn8iseZJz9qGBQKbA3pGw8r1iDrKptv95rSm9GymLaay+yC3YqnUlKk2RdeE0E8OSF2S8iz36mb3/6uAz0heckXPSXyaQnfuo4UBQB7d7jMXYJv0mYu6pJOXjdo0PHb++sleYkEOXHKlRWlTmZEczsBNpkpogDShJb7I4qbf+Vv0aERc2Y5KtAs5DKbwEwEdHkw10a8lE425Acg9JxqWeFuXP0k3LBRfodU8p77CkHuEyaLoeqAb0wbjgpkmnmDM/B/yLJzo49ovmvMV4G5FY4QlIyIudh7qQAGo6i0uOPrwE8V0QbtD3qjYb12Rx4G5uewX32cEQVTrFI23Nar91tkPl2pJxNUxyGpagsbmbAh39VantNCTu4gMKW9U4z3XQ=
after_script:
- npm run cover
- npm run codeclimate
